os: osx
language: generic
osx_image: xcode10.1
before_script:
- git clone https://github.com/flutter/flutter.git -b beta
- export PATH=$PATH:`pwd`/flutter/bin
script:
- flutter doctor
- flutter packages get
- flutter test
deploy:
  provider: script
  script:
  - flutter test
  on:
    tags: true
cache:
  directories:
  - "$HOME/.pub-cache"
notifications:
  slack:
    secure: gnwseASIusjskNBH84tzF3VmXf899d0U8ijgZMXLdriEGALYe7l42ycevH5fu15VJ31c8OnUcbKWLGnmbhAlmRDyF9fwAltZn3rXC2aeZC2XedtVQXmvg0AI4U3NYG6aokWnRANGaUcvFW6WB0CKBgqWzgsUmbpbZqyKfokDx+VAeivNu990OY7Qg4JyaQwP0q3tmzRbM+ib3fiILi1cbj66kcWhqV4l8EWw6uBoS/bDktrbspCYvsYwoU6K9RwjSxAfbp+mevKd+oRQ6y7mEciD7Lgh4CUd3w09xvfsxHtkB9ukdd8OYOxN2/TPZEepGwRVsIVz9ZwSiR7l4cd+vVMdVIt574OqTe0Cp6lpPKEvG30+aQd6s99k/9yi9z8eRTJGgsAkUX7FmULxxIKvHfDQq6hnuUgxn26xYu4bdAMa9dzglzvqfSbQ1SSYGxMLR7svsRRZP1e/AdAsnjEzo3PIm09q924oT1rAT/UpXlyimYNGqGwAHbGF4ldl5LcSk/M29KLGM3TjhBDBJ0Mo7OyzY2MOdSAN0brjbiqPrcgTt66EK8EnNls6OE88WIm0d4SUkH4EuqW7YULPdycuJZ6qcilVQ6dHC8Pe5PZ6USLcpPeq6yQnDO62qiFiorkR3vmmJB+1blvfDYKxNTGpGzJfNTpg1TAC4Jk2qhuFOKA=
